@startuml exercice2
class Pokemon {
    - int id
    - String name
    - String type
}

class PokemonService {
    + getPokemons() :  Iterable<Pokemon>
    + getPokemonsById(int id) : Pokemon
}

class PokemonViewModel {
    - StringProperty nameProperty
    - IntegerProperty idProperty
    - StringProperty typeProperty
    - update()
}

class PokemonView {
    + PokemonView(PokemonViewModel pvm)
    - update(ActionEvent evt)
}

Pokemon -[hidden]--> PokemonService

PokemonView -right- PokemonViewModel : Bindings

PokemonViewModel -up- PokemonService

PokemonViewModel -right- Pokemon

@enduml